import { Asignatura } from './asignatura';

//let comentario: ["Aún no hay comentarios"];

export const ASIGNATURAS: Asignatura[] = [
  { id: 1, nombre: 'ERP', imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQrg5MCALsyLvttGYeCAJBg-VCfgM-a3kVaHA&usqp=CAU', descripcion:"Aprenda sobre el manejo inteligente de la contabilidad a través de los ERP", profesor:"Eduardo Migliaro", comentarios: ["primer comentario","puede que hayan mas comentarios"], valoracion: 2.6, clave: "OII435"},
  { id: 2, nombre: 'Ciberseguridad', imagen:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTMETRh9ouTgq8DKSziTvd3seYlkMuHYYbPZg&usqp=CAU', descripcion:"Aprenda en que consiste realmente hackear y como proteger sus sistemas informáticos", profesor:"Sebasián Berrios", comentarios: ["Aún no hay comentarios"], valoracion: 4.2, clave:"OII440"},
  { id: 3, nombre: 'Experiencia del consumidor', imagen:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTziiFZxq0ZB4JCeewbeDdRUSnEH8ROLcF0KA&usqp=CAU', descripcion:"Asegurese de mantener a sus clientes contentos con las herramientas que le otorga este curso", profesor:"Alexandru Rusu", comentarios: ["comentario1","comentario2","comentario3"], valoracion: 4.5, clave:"OII441"},
  { id: 4, nombre: 'Entrenamiento y vida saludable', imagen:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSIR8P-MCHPM9i_X0NXry1usZu9y4DDk74BWw&usqp=CAU', descripcion:"No descuide su salud y aprenda en este curso como mantener su cuerpo y mente sanos", profesor:"Pendiente", comentarios: ["Aún no hay comentarios"], valoracion: 4, clave:"OII434"},
  { id: 5, nombre: 'Interacción usuario-computador', imagen:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRprv2rLD5z8R5Ia3gKKWk0plU8bwIodMIm-g&usqp=CAU', descripcion:"Este curso ofrece las distinciones necesarias para tener en cuenta en como el cliente interactuará con su software", profesor:"Alexandru Rusu", comentarios: ["Aún no hay comentarios"], valoracion: 4.2, clave:"OII436"},
  { id: 6, nombre: 'English for computing work', imagen:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTJ_0bq03rNDeNiK2IVhfTDSpxqJ5uuRBveSw&usqp=CAU', descripcion:"El inglés es una herramienta que nunca debe descuidarse, mejore su inglés para su área con este curso", profesor:"Nicole Boye" , comentarios: ["Aún no hay comentarios"], valoracion: 3.6, clave:"OII438"},
  { id: 7, nombre: 'Sistemas educativos inteligentes', imagen:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRBKp9O-Iy5LzoOQVXkeX6ATtoKdD-LxM1-Fg&usqp=CAU', descripcion:"Un área que está esperando por sus innovaciones para mejorar la educación de niños en Chile", profesor:"Claudio Cubillos" , comentarios: ["Aún no hay comentarios"], valoracion: 3.7, clave:"OII439"},
  { id: 8, nombre: 'Machine learning', imagen:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTuxUilTcAyeQFFsezQPFD6xp8EZ5gtAK0iyQ&usqp=CAU', descripcion:"Aprenda a manejar la tecnología que se encuentra a la vanguardia en la actualidad", profesor:"Pendiente" , comentarios: ["Aún no hay comentarios"], valoracion: 3.6, clave:"OII443"},
  { id: 9, nombre: 'Ejemp9', imagen:'algo1', descripcion:"algo", profesor:"si" , comentarios: ["Aún no hay comentarios"], valoracion: 0, clave:"OII437"},
  { id: 10, nombre: 'Ejemp10', imagen:'algo2', descripcion:"algo", profesor:"si" , comentarios: ["Aún no hay comentarios"], valoracion: 0, clave:"OII445"}
];